#VERSION 0
;
CSY POPUP HELP
50030 "Otevře řadič. Upravte rozvrh objednávek a vygenerujte nové výrobní rozvrhy.":
50070 "Zachovejte tabulky dat.":
50100 "Přeneste data do a z aplikace Preactor a uvolněte rozvrh.":
50120 "Importuje objednávky z jiného systému.":
50130 "Importuje prostředky z jiného systému.":
50140 "Importuje atributy výrobku z jiného systému.":
50150 "Exportuje objednávky do jiného systému.":
50160 "Exportuje prostředky do jiného systému.":
50170 "Exportuje atributy výrobku do jiného systému.":
53020 "Vytvořte, upravte a odstraňte skupiny nastavení. Seskupte výrobky do rodin sdílejících podobné atributy. Tato funkce se používá k určení dob nastavení závislých na posloupnosti.":
53030 "Vytvořte, upravte a odstraňte skupiny prostředků. Jedná se o přirozené skupiny prostředků, které mohou provádět podobné operace.":
53040 "Vytvořte, upravte a odstraňte skupiny prostředků. Určete omezení, pod kterými budou prostředky pracovat. Stanovte matice dob nastavení.":
53050 "Vytvořte, upravte a odstraňte sekundární omezení. Operace načtené u prostředků mohou mít před spuštěním další požadavky, například požadavky na zaměstnance nebo nástroje.":
53060 "Vytvořte, upravte a odstraňte skupiny sekundárních omezení. Pomocí nich je možné například vytvořit výběr ze sady nástrojů.":
53100 "Změňte horizont rozvržení, možnosti zobrazení a posuny pro nejdřívější počáteční datum a datum splatnosti nových objednávek. Nastavte výchozí skripty událostí, které se spustí z nabídky Přenos dat.":
53110 "Vytvořte, upravte a odstraňte podrobnosti o zákaznících. Určete kontaktní informace a doby zásobníku pro doručování.":
53510 "Vytvořte, upravte a odstraňte atributy výrobku. Popište vlastnosti výrobků a použitých procesů. Asociujte s atributy hodnoty hodnocení, které se mají použít preferovanými pravidly rozvržení posloupností.":
53550 "Vytvořte, upravte a odstraňte atributy stavu objednávky. Definujte vzory použité u pruhů operací představující jednotlivé stavy.":
53560 "Vytvořte, upravte a odstraňte atributy operace. Popište vlastnosti operací výrobku. Asociujte s atributy hodnoty hodnocení, které se mají použít preferovanými pravidly rozvržení posloupností.":
58510 "Zkopíruje rozvrh připravený pro výrobu do dalších systémů a oznámí ostatním, že je k dispozici nový rozvrh.":
69100 "Možnosti konfigurace, publikování a zobrazení grafů ve formátu html.":
69110 "Možnosti konfigurace pro PCO. Editor adresáře a možnosti odesílání a přijímání textových zpráv.":
69120 "Možnosti konfigurace pro PESP. Editor skriptů událostí, možnosti pro definování vlastních akcí a nastavení časovaných událostí.":
69130 "Možnosti konfigurace pro skripty importu-exportu. Možnost k definování a spuštění skriptů importu-exportu.":
69140 "Možnosti konfigurace pro analýzu rozvrhu.":
;
