#VERSION 0
;
DEU POPUP HELP
50030 "Öffnet den Sequencer. Ändern Sie den Zeitplan von Aufträgen und erstellen Sie neue Produktionszeitpläne.":
50070 "Verwalten Sie Datentabellen.":
50100 "Übertragen Sie Daten an und von Preactor und geben Sie den Zeitplan frei.":
50120 "Importiert Aufträge aus einem anderen System.":
50130 "Importiert Ressourcen aus einem anderen System.":
50140 "Importiert Produktattribute aus einem anderen System.":
50150 "Exportiert Aufträge in ein anderes System.":
50160 "Exportiert Ressourcen in ein anderes System.":
50170 "Exportiert Produktattribute in ein anderes System.":
53020 "Erstellen, bearbeiten und löschen Sie Rüstgruppen. Gruppieren Sie Produkte in Familien, die gleiche Attribute haben. Wird verwendet, um planungsabhängige Rüstzeiten zu ermitteln.":
53030 "Erstellen, bearbeiten und löschen Sie Ressourcengruppen. Dies sind offensichtliche Gruppen von Ressourcen, die ähnliche Vorgänge ausführen können.":
53040 "Erstellen, bearbeiten und löschen Sie Ressourcen. Geben Sie Bedingungen an, unter denen die Ressourcen funktionieren. Erstellen Sie Rüstzeitmatrizen.":
53050 "Erstellen, bearbeiten und löschen Sie sekundäre Bedingungen. Für Vorgänge, die für Ressourcen geladen sind, gibt es möglicherweise weitere Anforderungen, etwa Personal oder Werkzeugbestückung, bevor der jeweilige Vorgang beginnen kann.":
53060 "Erstellen, bearbeiten und löschen Sie Gruppen von sekundären Bedingungen. Verwenden Sie diese z.B. zur Modellierung einer Auswahl von Werkzeugbestückungen.":
53100 "Ändern Sie den Planungshorizont, zeigen Sie Optionen und Offsets für frühestes Anfangs- und Fälligkeitsdatum für neue Aufträge an. Legen Sie die Standardereignisskripts fest, die aus dem Menü 'Datenübertragung' ausgeführt werden sollen.":
53110 "Erstellen, bearbeiten und löschen Sie Kundendetails. Geben Sie Kontaktinformationen sowie Lieferpufferzeiten an.":
53510 "Erstellen, bearbeiten und löschen Sie Produktattribute. Beschreiben Sie Merkmale der verwendeten Produkte und Prozesse. Verknüpfen Sie Rangfolgewerte mit Attributen, die für bevorzugte Reihenfolgeplanungsregeln verwendet werden sollen.":
53550 "Erstellen, bearbeiten und löschen Sie Auftragsstatusattribute. Definieren Sie Muster, die auf Vorgangsbalken zum Darstellen jedes Status verwendet werden sollen.":
53560 "Erstellen, bearbeiten und löschen Sie Vorgangsattribute. Beschreiben Sie Merkmale von Vorgängen eines Produkts. Verknüpfen Sie Rangfolgewerte mit Attributen, die für bevorzugte Reihenfolgeplanungsregeln verwendet werden sollen.":
58510 "Kopiert einen für die Produktion fertigen Zeitplan auf andere Systeme, und benachrichtigt andere Personen, dass ein neuer Zeitplan verfügbar ist.":
69100 "Optionen zum Konfigurieren, Veröffentlichen und Anzeigen von HTML-Diagrammen.":
69110 "Konfigurationsoptionen für PCO. Adressbuch-Editor und Optionen zum Senden und Empfangen von Textnachrichten.":
69120 "Konfigurationsoptionen für PESP. Ereignisskript-Editor, Optionen zum Definieren von benutzerdefinierten Aktionen sowie von Einstellungen für zeitlich festgelegte Ereignisse.":
69130 "Konfigurationsoptionen für Import/Export-Skripts. Option zum Definieren und Ausführen von Import/Export-Skripts.":
69140 "Konfigurationsoptionen für Zeitplananalyse.":
;
