#VERSION 0
;
HUN POPUP HELP
50030 "A sorrendvezérlő megnyitása, amellyel módosíthatja a rendelések ütemezését, illetve új termelési ütemezéseket hozhat létre.":
50070 "Adatbázistáblák karbantartása.":
50100 "Adatok átvitele a Preactor alkalmazásba, illetve exportálása az alkalmazásból, illetve az ütemezés megjelentetése.":
50120 "Rendelések importálása egy másik rendszerből.":
50130 "Erőforrások importálása egy másik rendszerből.":
50140 "Termékattribútumok importálása egy másik rendszerből.":
50150 "Rendelések exportálása egy másik rendszerbe.":
50160 "Erőforrások exportálása egy másik rendszerbe.":
50170 "Termékattribútumok exportálása egy másik rendszerbe.":
53020 "Beállítási csoportok létrehozása, módosítása és törlése. A termékeket a hasonló attribútumok alapján családokba rendezheti. Ez a sorrendfüggő beállítási idők meghatározására szolgál.":
53030 "Erőforráscsoportok létrehozása, módosítása és törlése. Ezek a hasonló műveletek elvégzésére alkalmas erőforrások természetes csoportjai.":
53040 "Erőforrások létrehozása, módosítása és törlése. Határozza meg az erőforrások működését szabályozó megkötéseket. Állítsa be az időmátrixokat.":
53050 "Másodlagos megkötések létrehozása, módosítása és törlése. Az erőforrásokra betöltött műveletekhez gyakran további (például dolgozókra vagy eszközökre vonatkozó) követelmények társulnak, amelyeknek teljesülnie kell, hogy a művelet megkezdődhessen.":
53060 "Másodlagos megkötések csoportjainak létrehozása, szerkesztése és törlése. Ezekkel például egy adott eszközkészlet kiválasztását modellezheti.":
53100 "Az ütemezési horizont módosítása, az új rendelésekre vonatkozó legkorábbi kezdési dátum, illetve határidő eltolásának és beállításainak megjelenítése. Állítsa be az alapértelmezés szerint futtatandó esemény-parancsprogramokat az Adatátvitel menüben.":
53110 "Ügyféladatok létrehozása, módosítása és törlése. Adja meg a kapcsolatfelvételi adatokat, valamint a szállítás időtartalékát.":
53510 "Termékattribútumok létrehozása, módosítása és törlése. Írja le a használt termékek és folyamatok jellemzőit. Társítson rangsorolási értékeket az attribútumokhoz a preferált sorrend ütemezésére szolgáló szabályok számára.":
53550 "Rendelésistátusz-attribútumok létrehozása, szerkesztése és törlése. Határozza meg a műveleti sávokban az egyes státuszok jelzésére használt mintákat.":
53560 "Műveletattribútumok létrehozása, módosítása és törlése. Írja le a termékhez kapcsolódó műveletek jellemzőit. Társítson rangsorolási értékeket az attribútumokhoz a preferált sorrend ütemezésére szolgáló szabályok számára.":
58510 "Az üzemkész ütemezések más rendszerekre másolása, illetve a többi felhasználó értesítése az új elérhető ütemezésről.":
69100 "A HTML-diagramok konfigurálására, közzétételére és megtekintésére szolgáló lehetőségek.":
69110 "A PCO beállításai. Címtárszerkesztő, illetve a szöveges üzenetek küldésére és fogadására szolgáló lehetőségek.":
69120 "A PESP beállításai. Esemény-parancsprogramok szerkesztője, az egyéni műveletek, illetve az időzített események beállításainak meghatározására szolgáló lehetőségek.":
69130 "Az importálási/exportálási parancsprogramok konfigurációs lehetőségei. Az importálási/exportálási parancsprogramok létrehozására, illetve futtatására szolgáló lehetőségek.":
69140 "Az Ütemezéselemzés funkció konfigurációs lehetőségei.":
;
