#VERSION 0
;
NLD POPUP HELP
50030 "Hiermee opent u de Sequencer. Voor het wijzigen van de planning van orders en het genereren van nieuwe productieschema's.":
50070 "Gegevenstabellen onderhouden.":
50100 "Gegevens overdragen naar en van Preactor en het schema vrijgeven.":
50120 "Hiermee importeert u orders vanaf een ander systeem.":
50130 "Hiermee importeert u resources vanaf een ander systeem.":
50140 "Hiermee importeert u productkenmerken vanaf een ander systeem.":
50150 "Hiermee exporteert u orders naar een ander systeem.":
50160 "Hiermee exporteert u resources naar een ander systeem.":
50170 "Hiermee exporteert u productkenmerken naar een ander systeem.":
53020 "Instelgroepen maken, bewerken en verwijderen. Producten groeperen in series met dezelfde kenmerken. Worden gebruikt om de reeks te bepalen afhankelijk van insteltijden.":
53030 "Resourcegroepen maken, bewerken en verwijderen. Dit zijn natuurlijke groepen resources waarmee soortgelijke bewerkingen kunnen worden uitgevoerd.":
53040 "Resources maken, bewerken en verwijderen. Beperkingen opgeven waaronder resources werken. Insteltijdmatrices vaststellen.":
53050 "Secundaire beperkingen maken, bewerken en verwijderen. Bewerkingen op resources kunnen aanvullende eisen hebben, bijvoorbeeld personeel of gereedschappen, voordat de handeling kan beginnen.":
53060 "Maak, bewerk of verwijder groepen met secundaire beperkingen. Gebruik deze bijvoorbeeld voor modelselectie van een toolingset.":
53100 "Planningshorizon wijzigen, opties en marges weergeven voor de vroegste begin- en einddatum voor nieuwe orders. De standaardgebeurtenisscripts instellen voor het menu Gegevensoverdracht.":
53110 "Klantgegevens maken, bewerken en verwijderen. Contactinformatie opgeven, alsmede leveringsbuffertijden.":
53510 "Productkenmerken maken, bewerken en verwijderen. Beschrijf de kenmerken van de producten en processen worden gebruikt. Koppel prioriteitswaarden aan kenmerken die worden gebruikt door de gewenste planningsreeksregels.":
53550 "Statuskenmerken maken, bewerken en verwijderen. Definieer de patronen die worden gebruikt op werkbalken voor elke status.":
53560 "Actiekenmerken maken, bewerken en verwijderen. Beschrijf de actiekenmerken van een product. Koppel prioriteitswaarden aan kenmerken worden gebruikt door de gewenste planningsreeksregels.":
58510 "Hiermee wordt een productierijp schema naar andere systemen gekopieerd en aan anderen gemeld dat een nieuw schema beschikbaar is.":
69100 "Opties voor het configureren, publiceren en weergeven van HTML-grafieken.":
69110 "Configuratieopties voor PCO. Adresboek-editor en opties voor het verzenden en ontvangen van sms-berichten.":
69120 "Configuratieopties voor PESP. Gebeurtenisscripts-editor, opties voor het definiëren van aangepaste acties en getimede gebeurtenisinstellingen.":
69130 "Configuratieopties voor import-/exportscripts. Optie voor het definiëren en uitvoeren van import-/exportscripts.":
69140 "Configuratieopties voor schema-analyse.":
;
