#VERSION 0
;
ITA POPUP HELP
50030 "Apre il sequenziatore. Modifica la schedulazione degli ordini e genera nuovi programmi di produzione.":
50070 "Mantiene le tabelle dati.":
50100 "Trasferisce i dati da Preactor e verso Preactor e rilascia la schedulazione.":
50120 "Importa ordini da un altro sistema.":
50130 "Importa risorse da un altro sistema.":
50140 "Importa gli attributi del prodotto da un altro sistema.":
50150 "Esporta gli ordini in un altro sistema.":
50160 "Esporta le risorse in un altro sistema.":
50170 "Esporta gli attributi del prodotto in un altro sistema.":
53020 "Consente di creare, modificare ed eliminare i gruppi di configurazioni. Raggruppa i prodotti in famiglie che condividono attributi simili. Utilizzato per determinare i tempi di configurazione dipendenti dalla sequenza.":
53030 "Consente di creare, modificare ed eliminare gruppi di risorse. Si tratta di gruppi naturali che possono eseguire operazioni simili.":
53040 "Consente di creare, modificare ed eliminare risorse. Specifica i vincoli entro cui operano le risorse. Stabilisce le matrici del tempo di configurazione.":
53050 "Consente di creare, modificare ed eliminare vincoli secondari. Le operazioni caricate nelle risorse possono presentare altri requisiti, ad esempio richiedere personale o attrezzi prima che l'operazione possa iniziare.":
53060 "Consente di creare, modificare ed eliminare gruppi di vincoli secondari. È utile, ad esempio, per effettuare selezioni da un gruppo di attrezzi.":
53100 "Consente di modificare l'orizzonte di schedulazione, le opzioni di visualizzazione e gli scostamenti per la data di inizio al più presto e la due date dei nuovi ordini. Imposta gli script degli eventi predefiniti che devono essere eseguiti dal menu Trasferimento dati.":
53110 "Consente di creare, modificare ed eliminare i dettagli del cliente. Specifica le informazioni di contatto e i tempi del buffer di consegna.":
53510 "Consente di creare, modificare ed eliminare gli attributi del prodotto. Descrive le caratteristiche dei prodotti e dei processi utilizzati. Associa valori di classificazione agli attributi da utilizzare in base alle regole di schedulazione delle sequenze preferite.":
53550 "Consente di creare, modificare ed eliminare gli attributi di stato dell'ordine. Definisce i motivi utilizzati nelle barre di funzionamento per rappresentare ogni stato.":
53560 "Consente di creare, modificare ed eliminare gli attributi delle operazioni. Descrive le caratteristiche delle operazioni di un prodotto. Associa valori di classificazione agli attributi da utilizzare in base alle regole di schedulazione delle sequenze preferite.":
58510 "Consente di copiare una schedulazione pronta per la produzione in altri sistemi e notifica agli altri utenti che è disponibile una nuova schedulazione.":
69100 "Opzioni per configurare, pubblicare e visualizzare grafici HTML.":
69110 "Opzioni di configurazione per PCO. Editor della rubrica e opzioni per inviare e ricevere messaggi di testo.":
69120 "Opzioni di configurazione per PESP. Editor degli script degli eventi, opzioni per definire le azioni personalizzate e le impostazioni degli eventi temporizzati.":
69130 "Opzioni di configurazione per gli script di importazione-esportazione. Opzione per definire ed eseguire gli script di importazione-esportazione.":
69140 "Opzioni di configurazione per l'Analisi della schedulazione.":
;
