#VERSION 0
;
ESP POPUP HELP
50030 "Abre el secuenciador. Modifica la programación de órdenes y genera programaciones de producción nuevas.":
50070 "Mantiene las tablas de datos.":
50100 "Transfiere los datos desde y hacia Preactor, y libera la programación.":
50120 "Importa las órdenes de otro sistema.":
50130 "Importa los recursos de otro sistema.":
50140 "Importa los atributos de producto de otro sistema.":
50150 "Exporta las órdenes a otro sistema.":
50160 "Exporta los recursos a otro sistema.":
50170 "Exporta los atributos de producto a otro sistema.":
53020 "Crea, edita y elimina los grupos de preparación. Agrupa los productos en familias que comparten atributos similares. Se utiliza para determinar los tiempos de preparación dependientes de la secuencia.":
53030 "Crea, edita y elimina los grupos de recursos. Son grupos naturales de recursos que pueden realizar operaciones similares.":
53040 "Crea, edita y elimina los recursos. Especifica las restricciones en las que operan los recursos. Establece las matrices de tiempo de la preparación.":
53050 "Crea, edita y elimina las restricciones secundarias. Las operaciones cargadas en los recursos pueden tener requisitos adicionales, por ejemplo, personal o herramientas, para que pueda iniciar la operación.":
53060 "Crea, edita y elimina los grupos de restricciones secundarias. Utiliza estos para modelar la selección de un conjunto de herramientas, por ejemplo.":
53100 "Modifica el horizonte de programación, las opciones de visualización y los desplazamientos de las fechas de inicio y de vencimiento más tempranas para órdenes nuevas. Fija las secuencias de comandos de eventos predeterminadas que se ejecutarán desde el menú Transferencia de datos.":
53110 "Crea, edita y elimina los detalles de cliente. Especifica la información de contacto, así como los márgenes de tiempo de entrega.":
53510 "Crea, edita y elimina los atributos de producto. Describe las características de los productos y procesos que se utilizan. Asocia los valores de clasificación con los atributos que se usarán mediante las reglas de programación de secuencias preferentes.":
53550 "Crea, edita y elimina los atributos de estatus de orden. Define los patrones utilizados en las barras de operación para representar cada estatus.":
53560 "Crea, edita y elimina los atributos de operación. Describe las características de las operaciones de un producto. Asocia los valores de clasificación con los atributos que se usarán mediante reglas de programación de secuencias preferentes.":
58510 "Copia un programa listo para producción en otros sistemas y notifica a otros usuarios que hay disponible una programación nueva.":
69100 "Opciones para configurar, publicar y ver diagramas html.":
69110 "Opciones de configuración para PCO. Editor de libreta de direcciones y opciones para enviar y recibir mensajes de texto.":
69120 "Opciones de configuración para PESP. Editor de secuencias de comandos de eventos, opciones para definir acciones personalizadas y ajustes de eventos programados.":
69130 "Opciones de configuración para secuencias de comandos de importación-exportación. Opción para definir y ejecutar secuencias de comandos de exportación-importación.":
69140 "Opciones de configuración para el análisis de programaciones.":
;
