#VERSION 0
;
ESN POPUP HELP
50030 "Abre el secuenciador. Modificar la programación de órdenes y generar programaciones de producción nuevas.":
50070 "Mantener tablas de datos.":
50100 "Transferir datos desde y hacia Preactor, y liberar la programación.":
50120 "Importa órdenes de otro sistema.":
50130 "Importa recursos de otro sistema.":
50140 "Importa atributos de producto de otro sistema.":
50150 "Exporta órdenes a otro sistema.":
50160 "Exporta recursos a otro sistema.":
50170 "Exporta atributos de producto a otro sistema.":
53020 "Crear, editar y eliminar grupos de ajuste inicial. Agrupar los productos en familias que comparten atributos similares. Se utiliza para determinar los tiempos de ajuste inicial dependientes de la secuencia.":
53030 "Crear, editar y eliminar grupos de recursos. Son grupos naturales de recursos que pueden realizar operaciones similares.":
53040 "Crear, editar y eliminar recursos. Especificar las restricciones en las que operan los recursos. Establecer matrices de tiempo de ajuste inicial.":
53050 "Crear, editar y eliminar restricciones secundarias. Las operaciones cargadas en los recursos pueden tener requisitos adicionales, por ejemplo, personal o herramientas, para que pueda iniciar la operación.":
53060 "Crea, edita y elimina los grupos de restricciones secundarias. Utiliza estos para modelar la selección de un conjunto de herramientas, por ejemplo.":
53100 "Modificar el horizonte de programación, las opciones de visualización y los desplazamientos de las fechas de inicio y de vencimiento más tempranas para órdenes nuevas. Fijar las secuencias de comandos de eventos predeterminadas que se ejecutarán desde el menú Transferencia de datos.":
53110 "Crear, editar y eliminar detalles de cliente. Especificar la información de contacto, así como los tiempos de reserva de entrega.":
53510 "Crear, editar y eliminar atributos de producto. Describir las características de los productos y procesos que se utilizan. Asociar los valores de clasificación a los atributos que se usarán mediante las reglas de programación de secuencias preferidas.":
53550 "Crear, editar y eliminar atributos de estatus de orden. Definir los patrones utilizados en las barras de operación para representar cada estatus.":
53560 "Crear, editar y eliminar atributos de operación. Describir las características de las operaciones de un producto. Asociar valores de clasificación a los atributos que se usarán mediante reglas de programación de secuencias preferidas.":
58510 "Copia un programa listo para producción en otros sistemas y notifica a otros usuarios que hay disponible una programación nueva.":
69100 "Opciones para configurar, publicar y ver diagramas html.":
69110 "Opciones de configuración para PCO. Editor de libreta de direcciones y opciones para enviar y recibir mensajes de texto.":
69120 "Opciones de configuración para PESP. Editor de secuencias de comandos de eventos, opciones para definir acciones personalizadas y ajustes de eventos programados.":
69130 "Opciones de configuración para secuencias de comandos de importación-exportación. Opción para definir y ejecutar secuencias de comandos de exportación-importación.":
69140 "Opciones de configuración para el análisis de programaciones.":
;
