#VERSION 0
;
PTB POPUP HELP
50030 "Abre o sequenciador. Modifica a programação dos pedidos e gera novas programações de produção.":
50070 "Mantém tabelas de dados.":
50100 "Transfere dados de e para o Preactor e libera a programação.":
50120 "Importa pedidos de outro sistema.":
50130 "Importa recursos de outro sistema.":
50140 "Importa atributos de produtos de outro sistema.":
50150 "Exporta pedidos para outro sistema.":
50160 "Exporta recursos para outro sistema.":
50170 "Exporta atributos de produtos para outro sistema.":
53020 "Cria, edita e exclui grupos de configuração. Agrupa produtos em famílias que compartilham atributos similares. Usado para determinar tempos de configuração dependentes de sequência.":
53030 "Cria, edita e exclui grupos de recursos. Estes são os grupos naturais de recursos que podem execitar operações similares.":
53040 "Cria, edita e exclui recursos. Especifica as restrições em que esses recursos operam. Estabelece matrizes de tempo de configuração.":
53050 "Cria, edita ou exclui restrições secundárias. As operações carregadas em recursos podem ter requisitos adicionais, por exemplo, pessoas ou ferramentas que são necessárias antes que a operação possa começar.":
53060 "Cria, edita ou exclui grupos de restrições secundárias. Use para modelar uma seleção a partir de um conjunto do ferramentas, por exemplo.":
53100 "Modifica o horizonte da programação, exibe opções para data de início mais cedo e data de entrega para novos pedidos. Define o script de evento padrão que será executado a partir do menu de transferência de dados.":
53110 "Cria, edita e exclui detalhes do cliente. Especifica informações de contato bem como prazos de entrega.":
53510 "Cria, edita e exclui atributos de produto. Descreve as características dos produtos e os processos que sendo usados. Associa valores de classificação a serem usados por regras de programação de sequência preferenciais.":
53550 "Cria, edita e exclui atributos de status do pedido. Define o padrão usado nas barras de operação para representar cada status.":
53560 "Cria, edita e exclui atributos de operação. Descreve características das operações de um produto. Associa valores de classificação para atributos a serem usados nas regras de programação de sequência de preferência.":
58510 "Copia uma programação pronta para produção para outros sistemas e notifica outros de que uma nova programação está disponível.":
69100 "Opções para configurar, publicar e visualizar gráficos html.":
69110 "Opções de configuração para PCO. Editor de catálogo de endereços e opções para enviar e receber mensagens de texto.":
69120 "Opções de configuração para PESP. Editor de scripts de eventos, opções para definir ações personalizadas e definições de eventos de calendário.":
69130 "Opções de configuração para scripts de importação/exportação. Opções para definir e executar scripts de importação/exportação.":
69140 "Opções de configuração para a análise de programação.":
;
