#VERSION 0
;
FRA POPUP HELP
50030 "Ouvre l'Ordonnancement. Modifier le planning des ordres et générer de nouveaux plannings de production.":
50070 "Maintenir les tables de données.":
50100 "Transférer les données de / vers Preactor et lancer le Planning.":
50120 "Importer les ordres depuis un autre système.":
50130 "Importer les ressources depuis un autre système.":
50140 "Importe les attributs de produit depuis un autre système.":
50150 "Exporter les ordres vers un autre système.":
50160 "Exporter les ressources vers un autre système.":
50170 "Exporte les attributs de produit vers un autre système.":
53020 "Créer, modifier et supprimer des groupes de réglages. Regrouper des produits en familles qui partagent les mêmes attributs. Utilisé pour déterminer les temps de changement dans le planning.":
53030 "Créer, modifier et supprimer des groupes de ressources. Ce sont des groupes de ressources qui peuvent effectuer des opérations similaires.":
53040 "Créer, modifier et supprimer des ressources. Renseigner les contraintes des différentes ressources. Etablir des matrices de temps de changement.":
53050 "Créer, modifier et supprimer des contraintes secondaires. Les opérations affectées à des ressources peuvent avoir des besoins complémentaires, par exemple un besoin de personnel ou d'outillage avant que l'opération puisse démarrer.":
53060 "Créer, éditer et détruire des groupes de contraintes secondaires. Utilisez ces groupes pour modéliser la sélection à partir d'un ensemble d'outillage, par exemple.":
53100 "Modifier l'horizon de planification et les options de démarrage au plus tôt et de date de livraison pour les nouveaux ordres. Définir les scripts d'événements par défaut qui sont exécutés depuis le menu Transfert de données.":
53110 "Créer, modifier et supprimer les informations clients. Indiquer des coordonnées du contact jusqu'aux marges de sécurité avant livraison.":
53510 "Créer, modifier et supprimer les caractéristiques articles. Décrire les caractéristiques des produits et des gammes utilisés. Associer des valeurs de classement aux caractéristiques à utiliser avec les règles d'ordonnancement préférées.":
53550 "Créer, modifier et supprimer les caractéristiques de statut des OF. Définir les motifs utilisés sur la barre d'opération pour représenter chaque statut.":
53560 "Créer, modifier et supprimer les caractéristiques des opérations. Décrire les caractéristiques des opérations d'un produit. Associer des valeurs de classement à utiliser lors des règles d'ordonnancement.":
58510 "Copie un planning prêt à être lancé vers un autre système et avertir les autres utilisateurs qu'un nouveau planning est disponible.":
69100 "Options permettant de configurer, publier et visualiser les graphiques html.":
69110 "Options de configuration pour le PCO. Editeur de carnet d'adresse et options pour envoyer et recevoir des messages de texte.":
69120 "Options de configuration du PESP. Editeur de script d'événement, options de définition des actions personnalisées et des paramètres temporels d'événement.":
69130 "Options de configuration pour les scripts d'import-export. Permet de définir et de lancer les scripts d'import-export.":
69140 "Options de configuration pour l'analyse de planification.":
;
