#VERSION 0
;
ENG POPUP HELP
50030 "Opens the sequencer. Modify the schedule of orders and generate new production schedules.":
50070 "Maintain data tables.":
50100 "Transfer data to and from Preactor and release the schedule.":
50120 "Imports orders from another system.":
50130 "Imports resources from another system.":
50140 "Imports product attributes from another system.":
50150 "Exports orders to another system.":
50160 "Exports resources to another system.":
50170 "Exports product attributes to another system.":
53020 "Create, edit and delete setup groups. Group products into families that share similar attributes. Used to determine sequence dependent setup times.":
53030 "Create, edit and delete resource groups. These are natural groups of resources that can perform similar operations.":
53040 "Create, edit and delete resources. Specify constraints under which resources operate. Establish setup time matrices.":
53050 "Create, edit and delete secondary constraints. Operations loaded onto resources may have additional requirements, for example personnel or tooling before the operation can start.":
53060 "Create, edit and delete groups of secondary constraints. Use these to model selection from a set of tooling for example.":
53100 "Modify scheduling horizon, display options and offsets for earliest start and due date for new orders. Set the default event scripts that are to run from the Data Transfer Menu.":
53110 "Create, edit and delete customer details. Specify contact information as well as delivery buffer times.":
53510 "Create, edit and delete product attributes. Describe characteristics of the products and processes being used. Associate ranking values to attributes to be used by preferred sequence scheduling rules.":
53550 "Create, edit and delete order status attributes. Define the patterns used on operation bars to represent each status.":
53560 "Create, edit and delete operation attributes. Describe characteristics of operations of a product. Associate ranking values to attributes to be used by preferred sequence scheduling rules.":
58510 "Copies a production-ready schedule to other systems and notifies others that a new schedule is available.":
69100 "Options to configure, publish and view html charts.":
69110 "Configuration options for PCO. Address book editor and options to send and receive text messages.":
69120 "Configuration options for PESP. Event scripts editor, options to define custom actions and timed event settings.":
69130 "Configuration options for import-export scripts. Option to define and run import-export scripts.":
69140 "Configuration options for Schedule Analysis.":
;
