#VERSION 0
;
PLK POPUP HELP
50030 "Otwiera generator harmonogramu. Zmodyfikuj harmonogram zleceń i utwórz nowe harmonogramy produkcji.":
50070 "Obsługa bazy danych.":
50100 "Prześlij dane do systemu Preactor i pobierz dane z systemu oraz udostępnij harmonogram.":
50120 "Importuje zlecenia z innego systemu.":
50130 "Importuje zasoby z innego systemu.":
50140 "Importuje atrybuty produktu z innego systemu.":
50150 "Eksportuje zlecenia do innego systemu.":
50160 "Eksportuje zasoby do innego systemu.":
50170 "Eksportuje atrybuty produktu do innego systemu.":
53020 "Twórz, edytuj i usuwaj grupy przezbrojeń. Grupuj produkty do postaci rodzin dzielących podobne atrybuty. Służy do określenia czasów przezbrojeń zależnych od kolejności.":
53030 "Twórz, edytuj i usuwaj grupy zasobów. Są to naturalne grupy zasobów, które zapewniają wykonywanie podobnych operacji.":
53040 "Twórz, edytuj i usuwaj zasoby. Określ ograniczenia działania zasobów. Ustaw formaty okresu konfiguracji.":
53050 "Twórz, edytuj i usuwaj ograniczenia drugorzędowe. Operacje przydzielone do zasobów mogą zawierać dodatkowe ograniczenia, np. dot. osób lub narzędzi wymaganych przed rozpoczęciem operacji.":
53060 "Twórz, edytuj i usuwaj grupy ograniczeń drugorzędowych. Służą one na przykład do wyboru modelu z zestawu narzędzi.":
53100 "Modyfikuj horyzont planowania, wyświetlaj opcje i przesunięcia w przypadku najwcześniejszych dat rozpoczęcia i terminów realizacji zleceń. Ustaw domyślne skrypty zdarzeń uruchamiane z poziomu menu transferu danych.":
53110 "Twórz, edytuj i usuwaj detale klientów. Określ informacje kontaktowe oraz marginesy czasowe dostaw.":
53510 "Twórz, edytuj i usuwaj atrybuty produktów. Opisuj charakterystyki produktów i używane procesy. Łącz wartości rangi z atrybutami z przeznaczeniem do używania przez preferowane reguły planowania harmonogramowanie.":
53550 "Twórz, edytuj i usuwaj atrybuty statusu zlecenia. Definiuj szyki używane na paskach operacji w celu reprezentowania każdego statusu.":
53560 "Twórz, edytuj i usuwaj atrybuty operacji. Opisuj charakterystyki operacji w przypadku produktów. Łącz wartości rangi z atrybutami z przeznaczeniem do używania przez preferowane reguły planowania harmonogramowanie.":
58510 "Kopiuje harmonogram gotowy do produkcji do innych systemów i powiadamia inne osoby o dostępności nowego harmonogramu.":
69100 "Opcje konfiguracji, publikowania i wyświetlania wykresów html.":
69110 "Opcje konfiguracji dla PCO. Edytor książki adresowej i opcje wysyłania i odbierania wiadomości tekstowych.":
69120 "Opcje konfiguracji dla PESP. Edytor skryptów zdarzeń i opcje definiowania czynności niestandardowych oraz ustawienia zdarzeń zaplanowanych.":
69130 "Opcje konfiguracji związane ze skryptami importowania i eksportowania. Opcja definiowania i uruchamiania skryptów importowania i eksportowania.":
69140 "Opcje konfiguracji analizy harmonogramu.":
;
